name: compile solcjs
on: [push]
jobs:
  can-contract-compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install -g solc
      - run: solcjs --version
      - run: pwd
      - run: head -1 /home/runner/work/openzeppelin-contracts/openzeppelin-contracts/contracts/testFile.sol
      - run: solcjs --base-path /home/runner/work/openzeppelin-contracts/openzeppelin-contracts/contracts --bin /home/runner/work/openzeppelin-contracts/openzeppelin-contracts/contracts/testFile.sol
      - run: find -E ./ -regex ".*\.(sol|jpeg)" > log
      - run: awk '{sub(".//contracts/","import \"./")}1' log > output.sol
      - run: awk '{sub("sol", "sol\";")}1' output.sol > log && mv log output.sol
      - run: awk '{sub(".//", "//")}1' output.sol > log && mv log output.sol
      - run: printf '%s\n' "// SPDX-License-Identifier:" " MIT" 'pragma solidity >=0.6.0 <0.9.0;' | cat - output.sol > log && mv log output.sol
