name: compile solcjs
on: [push]
jobs:
  can-contract-compile:
    runs-on: [macos-latest]
    steps:
      - uses: actions/checkout@v2
#       - uses: actions/setup-node@v1
#       - run: npm install -g solc
      - run: find -E ../ -regex ".*\.(sol|jpeg)"
        continue-on-error: true
      - run: awk --version
        continue-on-error: true
      - run: printf --version
#       - run: solcjs --version
#       - run: solcjs --base-path /home/runner/work/openzeppelin-contracts/openzeppelin-contracts/contracts --bin /home/runner/work/openzeppelin-contracts/openzeppelin-contracts/contracts/testFile.sol
